
INSERT INTO `versions` ( `ismajorrelease`,`version`,`id`,`filename`,`createdat` ) VALUES ( 0,'1.1 Beta 1',19,'cfwheels.1.1-beta-1.zip','2010-09-10' );
INSERT INTO `versions` ( `ismajorrelease`,`version`,`id`,`filename`,`createdat` ) VALUES ( 1,1.1,20,'cfwheels.1.1.zip','2010-09-11' );
INSERT INTO `functionsections` ( `name`,`parentfunctionsectionid`,`ordering`,`slug` ) VALUES ( 'Provides Functions',5,1,'provides' );
INSERT INTO `functionsections` ( `name`,`parentfunctionsectionid`,`ordering`,`slug` ) VALUES ( 'Provides Functions',6,1,'provides' );
INSERT INTO `functionsections` ( `name`,`parentfunctionsectionid`,`ordering`,`slug` ) VALUES ( 'Form Association Functions',4,1,'forms-association' );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 1,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 2,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 3,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 4,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 5,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 6,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 7,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 8,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 9,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 10,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 11,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 12,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 13,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 14,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 15,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 16,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 17,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 18,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 19,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 20,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 21,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 22,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 24,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 25,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 26,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 27,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 28,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 29,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 30,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 31,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 32,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 33,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 34,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 35,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 36,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 37,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 38,20 );
INSERT INTO `functionsectionversions` ( `functionsectionid`,`versionid` ) VALUES ( 39,20 );
